### ISSUE TITLE
[Old Sidebar] Sidebar showing up on pages where it shouldn't

### ISSUE THREAD

**Issue by hujgup** [estufar/extensions#2]
Broswer: Chrome 48

Steps to replicate:
1. Open the Tumblr dashboard, go into the XKit settings menu and check that the settings page looks like this:

![this](https://cloud.githubusercontent.com/assets/8285143/13286168/7853f7ee-db53-11e5-8da3-5cca8c08210f.png)
1. Open a second tab at the following URL: [https://www.tumblr.com/docs/en/api/v2](https://www.tumblr.com/docs/en/api/v2)

You should see something like  this:

![this](https://cloud.githubusercontent.com/assets/8285143/13286175/940cb714-db53-11e5-9b0e-1ff5da56ab4e.png)

In extension settings, checking the "Only run on the dashboard" box fixes the problem, but it of course also removes it from things like the "Likes" page.

Likely cause: An element with I.D. "right_column" appears on both pages, but they are not both representing the same thing. A more robust check is required.

Dashboard:

![Dashboard](https://cloud.githubusercontent.com/assets/8285143/13286365/05f28470-db55-11e5-8e96-cf8482c7d121.png)

API Page:

![API page](https://cloud.githubusercontent.com/assets/8285143/13286374/15a2416c-db55-11e5-95ef-19c6b970f0e6.png)

**Comment by estufar** [comment]
Yep, I've gone ahead and made a fix to disable running the extension on pages where this is an issue. Since this extension has been added into New XKit's gallery, it's now being maintained in the New XKit repository and the version on this one isn't being updated anymore. I've made a [pull request](https://github.com/new-xkit/XKit/pull/975) on New XKit's repository with these updates and assuming all goes well it should be updated soon.
